
import {APP_VERSION, defaultState, loadState, saveState, getAllPdfs, savePdf, removePdf, clearPdfs, round2} from "./storage-v600.js";
import {drawLineChart, drawDonutChart, drawPercentBars} from "./charts.js";

const state=loadState();
let calendarCursor=new Date();
let deferredInstallPrompt=null;
const $=id=>document.getElementById(id);
const money=value=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value||0));
const dateText=value=>new Date(`${value}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
const shiftDate=(value,days)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const numberValue=id=>Number($(id)?.value||0);
const sum=values=>round2(values.reduce((a,b)=>a+Number(b||0),0));
function toast(message){const e=$("toast");e.textContent=message;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function persist(){saveState(state)}

function totals(records=state.records){
  return records.reduce((a,r)=>({
    gross:round2(a.gross+r.gross),taxes:round2(a.taxes+r.totalTaxes),
    deductions:round2(a.deductions+r.totalDeductions),net:round2(a.net+r.net),
    federal:round2(a.federal+r.taxes.federal),medicare:round2(a.medicare+r.taxes.medicare),
    social:round2(a.social+r.taxes.social),employerMatch:round2(a.employerMatch+Number(r.employerMatch||0))
  }),{gross:0,taxes:0,deductions:0,net:0,federal:0,medicare:0,social:0,employerMatch:0});
}
function years(){const s=new Set(state.records.map(r=>r.payDate.slice(0,4)));s.add(new Date().getFullYear().toString());return [...s].sort()}
function fillYearSelect(el,all=false){const current=el.value;el.innerHTML=(all?'<option value="all">All years</option>':"")+years().map(y=>`<option value="${y}">${y}</option>`).join("");if([...el.options].some(o=>o.value===current))el.value=current;else if([...el.options].some(o=>o.value==="2026"))el.value="2026"}
function frequencyDays(){return state.profile.frequency==="weekly"?7:state.profile.frequency==="monthly"?30:14}
function expectedPaydays(count=12){const dates=state.records.map(r=>new Date(`${r.payDate}T12:00:00`)).sort((a,b)=>a-b);let d=dates.at(-1)||new Date(`${state.profile.joiningDate}T12:00:00`);const out=[];for(let i=0;i<count;i++){d=new Date(d);d.setDate(d.getDate()+frequencyDays());out.push(new Date(d))}return out}
function tenureText(){const s=new Date(`${state.profile.joiningDate}T12:00:00`),n=new Date();let y=n.getFullYear()-s.getFullYear(),m=n.getMonth()-s.getMonth(),d=n.getDate()-s.getDate();if(d<0){d+=new Date(n.getFullYear(),n.getMonth(),0).getDate();m--}if(m<0){m+=12;y--}return `${y} Years, ${m} Months, ${d} Days`}
function nextPaydayText(){const n=new Date(),d=expectedPaydays(30).find(x=>x>=n)||expectedPaydays(1)[0];return d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}
function applyTheme(theme=state.theme){state.theme=theme;persist();const dark=theme==="dark"||(theme==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";$("themeQuickToggle").textContent=dark?"Light mode":"Dark mode";setTimeout(renderCharts,40)}
function updateBranding(){const c=state.profile.company||"Company",n=state.profile.name||"Employee";$("brandCompany").textContent=c;$("brandEmployee").textContent=n;$("brandLogo").textContent=c.charAt(0).toUpperCase()||"P";document.title=`${n} Payroll Hub`}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===name));const t=$(`${name}View`);if(!t)return;t.classList.add("active");$("pageTitle").textContent={dashboard:"Dashboard",payroll:"Payroll Entry",reports:"Reports",analytics:"Analytics",calendar:"Pay Calendar",vault:"PDF Vault",settings:"Profile & Settings"}[name];$("sidebar").classList.remove("open");if(name==="vault")renderPdfList();if(name==="settings")renderSettings();renderAll()}

function autoFillPayPeriod(){if(!$("payDate").value)return;const days=frequencyDays();$("periodEnd").value=shiftDate($("payDate").value,-Math.max(1,Math.round(days/2)));$("periodStart").value=shiftDate($("periodEnd").value,-days+1)}
function getEarnings(){return{regular:numberValue("regular"),overtime:numberValue("overtime"),bonus:numberValue("bonus"),commission:numberValue("commission"),reimbursement:numberValue("reimbursement"),other:numberValue("otherEarnings")}}
function getTaxes(){return{federal:numberValue("federal"),state:numberValue("stateTax"),local:numberValue("localTax"),medicare:numberValue("medicare"),social:numberValue("social"),other:numberValue("otherTax")}}
function getDeductions(){return{retirement:numberValue("retirement"),medical:numberValue("medicalDeduction"),dental:numberValue("dental"),vision:numberValue("vision"),hsa:numberValue("hsa"),life:numberValue("life"),other:numberValue("otherDeduction")}}
function calculatePay(){
  const gross=sum(Object.values(getEarnings())),taxes=sum(Object.values(getTaxes())),deductions=sum(Object.values(getDeductions())),net=round2(gross-taxes-deductions);
  $("gross").value=gross.toFixed(2);$("totalTaxes").value=taxes.toFixed(2);$("totalDeductions").value=deductions.toFixed(2);$("net").value=net.toFixed(2)
}
function formIds(){return["payDate","periodStart","periodEnd","rate","hours","regular","overtime","bonus","commission","reimbursement","otherEarnings","federal","stateTax","localTax","medicare","social","otherTax","retirement","medicalDeduction","dental","vision","hsa","life","otherDeduction","employerMatch","deposit1Label","deposit1Amount","deposit2Label","deposit2Amount","editIndex"]}
function clearPaycheckForm(){formIds().forEach(id=>{if($(id))$(id).value=""});$("recordPayBasis").value=state.profile.payBasis||"salary";["gross","totalTaxes","totalDeductions","net"].forEach(id=>$(id).value="0.00");$("payrollFormTitle").textContent="Add paycheck"}
function savePaycheck(){
  if(!$("payDate").value){toast("Enter a pay date.");return}
  calculatePay();
  const record={
    payDate:$("payDate").value,periodStart:$("periodStart").value||shiftDate($("payDate").value,-13),periodEnd:$("periodEnd").value||shiftDate($("payDate").value,-1),
    payBasis:$("recordPayBasis").value,rate:numberValue("rate"),hours:numberValue("hours"),
    earnings:getEarnings(),taxes:getTaxes(),deductions:getDeductions(),employerMatch:numberValue("employerMatch"),
    distributions:[
      {label:$("deposit1Label").value.trim(),amount:numberValue("deposit1Amount")},
      {label:$("deposit2Label").value.trim(),amount:numberValue("deposit2Amount")}
    ].filter(x=>x.label||x.amount),
    gross:numberValue("gross"),totalTaxes:numberValue("totalTaxes"),totalDeductions:numberValue("totalDeductions"),net:numberValue("net")
  };
  record.federal=record.taxes.federal;record.medicare=record.taxes.medicare;record.social=record.taxes.social;
  const i=$("editIndex").value;if(i==="")state.records.push(record);else state.records[Number(i)]=record;
  state.records.sort((a,b)=>a.payDate.localeCompare(b.payDate));persist();clearPaycheckForm();refreshYearSelects();renderAll();toast("Paycheck saved.")
}
window.editPaycheck=index=>{const r=state.records[index];if(!r)return;$("payDate").value=r.payDate;$("periodStart").value=r.periodStart;$("periodEnd").value=r.periodEnd;$("recordPayBasis").value=r.payBasis||"salary";$("rate").value=r.rate||"";$("hours").value=r.hours||"";
  const map={regular:r.earnings.regular,overtime:r.earnings.overtime,bonus:r.earnings.bonus,commission:r.earnings.commission,reimbursement:r.earnings.reimbursement,otherEarnings:r.earnings.other,federal:r.taxes.federal,stateTax:r.taxes.state,localTax:r.taxes.local,medicare:r.taxes.medicare,social:r.taxes.social,otherTax:r.taxes.other,retirement:r.deductions.retirement,medicalDeduction:r.deductions.medical,dental:r.deductions.dental,vision:r.deductions.vision,hsa:r.deductions.hsa,life:r.deductions.life,otherDeduction:r.deductions.other,employerMatch:r.employerMatch};
  Object.entries(map).forEach(([id,v])=>$(id).value=v||"");const d=r.distributions||[];$("deposit1Label").value=d[0]?.label||"";$("deposit1Amount").value=d[0]?.amount||"";$("deposit2Label").value=d[1]?.label||"";$("deposit2Amount").value=d[1]?.amount||"";$("editIndex").value=index;$("payrollFormTitle").textContent="Edit paycheck";calculatePay();showView("payroll");scrollTo({top:0,behavior:"smooth"})
};
window.deletePaycheck=index=>{if(confirm("Delete this paycheck?")){state.records.splice(index,1);persist();refreshYearSelects();renderAll();toast("Paycheck deleted.")}}

function payrollTable(records,actions=true){
  if(!records.length)return'<p class="helper">No payroll records found.</p>';
  return `<table><thead><tr><th>Pay date and period</th><th>Basis</th><th class="amount">Gross</th><th class="amount">Taxes</th><th class="amount">Deductions</th><th class="amount">Net</th>${actions?"<th>Actions</th>":""}</tr></thead><tbody>${records.map(r=>{const i=state.records.indexOf(r);return`<tr><td><strong>${dateText(r.payDate)}</strong><br><span>${dateText(r.periodStart)} to ${dateText(r.periodEnd)}</span></td><td>${r.payBasis||"Salary"}${r.hours?`<br><small>${r.hours} hrs @ ${money(r.rate)}</small>`:""}</td><td class="amount">${money(r.gross)}</td><td class="amount">${money(r.totalTaxes)}</td><td class="amount">${money(r.totalDeductions)}</td><td class="amount"><span class="badge">${money(r.net)}</span></td>${actions?`<td><div class="actions"><button class="secondary" onclick="editPaycheck(${i})">Edit</button><button class="danger" onclick="deletePaycheck(${i})">Delete</button></div></td>`:""}</tr>`}).join("")}</tbody></table>`
}
function renderPayrollTables(){const q=$("payrollSearch").value.toLowerCase(),y=$("payrollYear").value;const filtered=state.records.filter(r=>(y==="all"||r.payDate.startsWith(y))&&(!q||r.payDate.includes(q)||state.profile.company.toLowerCase().includes(q)));$("recentPayroll").innerHTML=payrollTable(state.records.slice(-5).reverse(),false);$("payrollTable").innerHTML=payrollTable(filtered,true)}
function monthlyTotals(year){return Array.from({length:12},(_,i)=>totals(state.records.filter(r=>r.payDate.startsWith(`${year}-${String(i+1).padStart(2,"0")}`))))}
function renderDashboard(){const y=$("dashboardYear").value||years().at(-1),rs=state.records.filter(r=>r.payDate.startsWith(y)),t=totals(rs),avg=rs.length?t.net/rs.length:0;$("dashboardName").textContent=state.profile.name;$("dashboardCompany").textContent=state.profile.company;$("joiningText").textContent=dateText(state.profile.joiningDate);$("tenureText").textContent=tenureText();$("frequencyText").textContent=state.profile.frequency;$("nextPayday").textContent=nextPaydayText();const p=state.profile.photo||"assets/avatar.png";$("dashboardPhoto").src=p;$("settingsPhoto").src=p;$("dashboardKpis").innerHTML=[["Gross Pay YTD",money(t.gross),"All earnings"],["Net Pay YTD",money(t.net),"Take-home pay"],["Taxes YTD",money(t.taxes),"Federal, state and payroll"],["Deductions YTD",money(t.deductions),"Benefits and other"],["Average Net",money(avg),`${rs.length} paychecks`]].map(x=>`<article class="card kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("")}
function renderReports(){const y=$("reportYear").value||years().at(-1),rs=state.records.filter(r=>r.payDate.startsWith(y)),t=totals(rs),avg=rs.length?t.net/rs.length:0;$("reportKpis").innerHTML=[["Annual Gross",money(t.gross),y],["Annual Net",money(t.net),y],["Total Taxes",money(t.taxes),"All tax types"],["Employee Deductions",money(t.deductions),"Benefits and other"],["Employer Match",money(t.employerMatch),"Employer contributions"]].map(x=>`<article class="card kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("");$("reportTaxSummary").innerHTML=[["Federal Tax",t.federal],["Medicare",t.medicare],["Social Security",t.social],["Total Taxes",t.taxes],["Total Deductions",t.deductions]].map(x=>`<div class="metric-row"><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join("");const m=monthlyTotals(y),names=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];$("monthlyReportTable").innerHTML=`<table><thead><tr><th>Month</th><th class="amount">Gross</th><th class="amount">Taxes</th><th class="amount">Deductions</th><th class="amount">Net</th></tr></thead><tbody>${m.map((x,i)=>`<tr><td>${names[i]}</td><td class="amount">${money(x.gross)}</td><td class="amount">${money(x.taxes)}</td><td class="amount">${money(x.deductions)}</td><td class="amount">${money(x.net)}</td></tr>`).join("")}</tbody></table>`}
function renderAnalytics(){const y=$("analyticsYear").value||years().at(-1),rs=state.records.filter(r=>r.payDate.startsWith(y)),t=totals(rs),avg=rs.length?t.net/rs.length:0;$("analyticsKpis").innerHTML=[["Avg Gross",money(rs.length?t.gross/rs.length:0),"Per paycheck"],["Avg Net",money(avg),"Per paycheck"],["Tax Rate",t.gross?`${(t.taxes/t.gross*100).toFixed(1)}%`:"0%","All taxes"],["Deduction Rate",t.gross?`${(t.deductions/t.gross*100).toFixed(1)}%`:"0%","Employee deductions"],["Employer Match",money(t.employerMatch),"Year total"]].map(x=>`<article class="card kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("");const c=rs.at(-1),p=rs.at(-2);$("comparisonGrid").innerHTML=!c||!p?'<p class="helper">At least two paychecks are required.</p>':[["Gross",c.gross,p.gross],["Taxes",c.totalTaxes,p.totalTaxes],["Deductions",c.totalDeductions,p.totalDeductions],["Net",c.net,p.net],["Employer Match",c.employerMatch,p.employerMatch]].map(([n,a,b])=>{const d=round2(a-b),pct=b?d/b*100:0;return`<div class="comparison-card"><span>${n}</span><strong>${money(a)}</strong><small class="${d>=0?"up":"down"}">${d>=0?"+":""}${money(d)} (${pct.toFixed(1)}%)</small></div>`}).join("")}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$("calendarTitle").textContent=calendarCursor.toLocaleDateString("en-US",{month:"long",year:"numeric"});const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),actual=new Set(state.records.map(r=>r.payDate)),expected=new Set(expectedPaydays(40).map(d=>d.toISOString().slice(0,10))),today=new Date().toISOString().slice(0,10);let html=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="calendar-head">${d}</div>`).join("");for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10),cls=["calendar-day"];if(d.getMonth()!==m)cls.push("muted");if(iso===today)cls.push("today");if(actual.has(iso))cls.push("payday");else if(expected.has(iso))cls.push("expected");html+=`<div class="${cls.join(" ")}"><span class="day-number">${d.getDate()}</span>${actual.has(iso)?'<span class="day-tag">Recorded</span>':expected.has(iso)?'<span class="day-tag">Expected</span>':""}</div>`}$("calendarGrid").innerHTML=html;$("upcomingEvents").innerHTML=expectedPaydays(6).map(d=>`<div class="event-item"><strong>${d.toLocaleDateString()}</strong><span>Expected payroll date</span></div>`).join("")}
function renderCharts(){const labels=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],dy=$("dashboardYear").value||years().at(-1),dm=monthlyTotals(dy);drawLineChart($("dashboardTrendChart"),labels,[{label:"Gross",data:dm.map(x=>x.gross),color:"#5b2c6f"},{label:"Net",data:dm.map(x=>x.net),color:"#00a6a6"}]);const dt=totals(state.records.filter(r=>r.payDate.startsWith(dy)));drawDonutChart($("dashboardDonutChart"),["Net","Taxes","Deductions","Employer Match"],[dt.net,dt.taxes,dt.deductions,dt.employerMatch]);const ry=$("reportYear").value||dy,rm=monthlyTotals(ry);drawLineChart($("reportTrendChart"),labels,[{label:"Gross",data:rm.map(x=>x.gross),color:"#5b2c6f"},{label:"Net",data:rm.map(x=>x.net),color:"#00a6a6"}]);const ay=$("analyticsYear").value||dy,ar=state.records.filter(r=>r.payDate.startsWith(ay));drawLineChart($("analyticsTrendChart"),ar.map(r=>dateText(r.payDate).replace(`, ${ay}`,"")),[{label:"Net",data:ar.map(r=>r.net),color:"#00a6a6"}],300);drawPercentBars($("analyticsRateChart"),ar.map(r=>dateText(r.payDate).slice(0,6)),[{label:"Tax rate",data:ar.map(r=>r.gross?r.totalTaxes/r.gross*100:0),color:"#5b2c6f"},{label:"Deduction rate",data:ar.map(r=>r.gross?r.totalDeductions/r.gross*100:0),color:"#f59e0b"}])}
function exportCsv(records=state.records,filename="Universal_Payroll_Report.csv"){const rows=[["Pay Date","Period Start","Period End","Pay Basis","Rate","Hours","Gross","Federal","State","Local","Medicare","Social Security","Other Tax","Total Taxes","Retirement","Medical","Dental","Vision","HSA/FSA","Life","Other Deduction","Total Deductions","Employer Match","Net Pay"]];records.forEach(r=>rows.push([r.payDate,r.periodStart,r.periodEnd,r.payBasis,r.rate,r.hours,r.gross,r.taxes.federal,r.taxes.state,r.taxes.local,r.taxes.medicare,r.taxes.social,r.taxes.other,r.totalTaxes,r.deductions.retirement,r.deductions.medical,r.deductions.dental,r.deductions.vision,r.deductions.hsa,r.deductions.life,r.deductions.other,r.totalDeductions,r.employerMatch,r.net]));downloadBlob(rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),filename,"text/csv")}
function downloadBlob(content,name,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderSettings(){$("profileName").value=state.profile.name;$("profileCompany").value=state.profile.company;$("profileEmployeeId").value=state.profile.employeeId||"";$("profileDepartment").value=state.profile.department||"";$("profileCompanyAddress").value=state.profile.companyAddress||"";$("profilePayBasis").value=state.profile.payBasis||"salary";$("profileJoining").value=state.profile.joiningDate;$("profileFrequency").value=state.profile.frequency;$("settingsPhoto").src=state.profile.photo||"assets/avatar.png";$("notificationStatus").textContent=`Status: ${"Notification" in window?Notification.permission:"unsupported"}`;$("reminderDays").value=state.notifications.daysBefore;$("missingReminder").checked=state.notifications.missingPaycheck;$("backupReminder").checked=state.notifications.backupReminder;renderNotificationList()}
function saveProfile(){state.profile.name=$("profileName").value.trim()||"Employee";state.profile.company=$("profileCompany").value.trim()||"Company";state.profile.employeeId=$("profileEmployeeId").value.trim();state.profile.department=$("profileDepartment").value.trim();state.profile.companyAddress=$("profileCompanyAddress").value.trim();state.profile.payBasis=$("profilePayBasis").value;state.profile.joiningDate=$("profileJoining").value;state.profile.frequency=$("profileFrequency").value;persist();$("recordPayBasis").value=state.profile.payBasis;renderAll();toast("Profile saved.")}
function handlePhoto(file){const r=new FileReader();r.onload=()=>{state.profile.photo=r.result;persist();renderAll();toast("Photo updated.")};r.readAsDataURL(file)}
function buildNotifications(){const a=[];if(state.notifications.backupReminder&&!state.notifications.lastBackup)a.push({title:"Backup recommended",body:"Download a full backup."});return a}
function renderNotificationList(){const a=buildNotifications();$("notificationList").innerHTML=a.length?a.map(x=>`<div class="event-item"><strong>${x.title}</strong><span>${x.body}</span></div>`).join(""):'<p class="helper">No current alerts.</p>'}
async function enableNotifications(){if(!("Notification" in window)){toast("Notifications unsupported.");return}const p=await Notification.requestPermission();renderSettings();if(p==="granted")new Notification("Payroll Hub",{body:"Notifications enabled."})}
function saveNotificationSettings(){state.notifications.daysBefore=Number($("reminderDays").value);state.notifications.missingPaycheck=$("missingReminder").checked;state.notifications.backupReminder=$("backupReminder").checked;persist();toast("Reminder settings saved.")}
async function renderPdfList(){const docs=await getAllPdfs(),q=$("pdfSearch").value.toLowerCase();$("pdfList").innerHTML=docs.filter(d=>d.name.toLowerCase().includes(q)).map(d=>`<div class="document-card"><strong>${d.name}</strong><span>${(d.size/1024).toFixed(1)} KB</span><div class="document-actions"><button class="secondary" onclick="openStoredPdf('${d.id}')">Open</button><button class="danger" onclick="deleteStoredPdf('${d.id}')">Delete</button></div></div>`).join("")||'<p class="helper">No PDF files stored.</p>'}
window.openStoredPdf=async id=>{const d=(await getAllPdfs()).find(x=>x.id===id);if(d)window.open(URL.createObjectURL(d.blob),"_blank")};window.deleteStoredPdf=async id=>{if(confirm("Delete PDF?")){await removePdf(id);renderPdfList()}};
async function uploadPdfs(files){for(const f of files)if(f.type==="application/pdf")await savePdf({id:crypto.randomUUID(),name:f.name,size:f.size,created:new Date().toISOString(),blob:f});renderPdfList();toast("PDF uploaded.")}
function backupPayroll(){state.notifications.lastBackup=new Date().toISOString();persist();downloadBlob(JSON.stringify({version:APP_VERSION,state},null,2),"Payroll_Backup.json","application/json")}
async function backupFull(){state.notifications.lastBackup=new Date().toISOString();persist();const docs=await getAllPdfs();downloadBlob(JSON.stringify({version:APP_VERSION,state,pdfNames:docs.map(d=>d.name)},null,2),"Payroll_Full_Backup.json","application/json");toast("Backup downloaded.")}
async function resetEverything(){if(confirm("Delete all local payroll data?")){Object.assign(state,defaultState());persist();await clearPdfs();refreshYearSelects();renderAll()}}
function refreshYearSelects(){fillYearSelect($("dashboardYear"));fillYearSelect($("payrollYear"),true);fillYearSelect($("reportYear"));fillYearSelect($("analyticsYear"))}
function renderAll(){persist();updateBranding();renderDashboard();renderPayrollTables();renderReports();renderAnalytics();renderCalendar();renderSettings();renderCharts()}

function bindEvents(){
  document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));document.querySelectorAll("[data-view-link]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.viewLink)));
  document.querySelectorAll(".calc-input").forEach(e=>e.addEventListener("input",calculatePay));$("payDate").addEventListener("change",autoFillPayPeriod);$("savePaycheck").addEventListener("click",savePaycheck);$("clearPaycheck").addEventListener("click",clearPaycheckForm);$("quickAdd").addEventListener("click",()=>showView("payroll"));
  $("payrollSearch").addEventListener("input",renderPayrollTables);$("payrollYear").addEventListener("change",renderPayrollTables);$("dashboardYear").addEventListener("change",()=>{renderDashboard();renderCharts()});$("reportYear").addEventListener("change",()=>{renderReports();renderCharts()});$("analyticsYear").addEventListener("change",()=>{renderAnalytics();renderCharts()});$("exportPayrollCsv").addEventListener("click",()=>exportCsv());$("exportReportCsv").addEventListener("click",()=>exportCsv(state.records.filter(r=>r.payDate.startsWith($("reportYear").value)),`Payroll_${$("reportYear").value}.csv`));$("printReport").addEventListener("click",()=>print());
  $("calendarPrevious").addEventListener("click",()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()});$("calendarNext").addEventListener("click",()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()});
  $("pdfUpload").addEventListener("change",e=>uploadPdfs(e.target.files));$("pdfSearch").addEventListener("input",renderPdfList);$("photoUpload").addEventListener("change",e=>e.target.files[0]&&handlePhoto(e.target.files[0]));$("saveProfile").addEventListener("click",saveProfile);$("enableNotifications").addEventListener("click",enableNotifications);$("saveNotificationSettings").addEventListener("click",saveNotificationSettings);$("fullBackup").addEventListener("click",backupFull);$("payrollBackup").addEventListener("click",backupPayroll);$("lightTheme").addEventListener("click",()=>applyTheme("light"));$("darkTheme").addEventListener("click",()=>applyTheme("dark"));$("systemTheme").addEventListener("click",()=>applyTheme("system"));$("themeQuickToggle").addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark"));$("resetEverything").addEventListener("click",resetEverything);$("menuBtn").addEventListener("click",()=>$("sidebar").classList.toggle("open"));addEventListener("resize",()=>setTimeout(renderCharts,100))
}
function initialize(){bindEvents();refreshYearSelects();$("todayText").textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"});$("versionText").textContent=`Version ${APP_VERSION}`;$("recordPayBasis").value=state.profile.payBasis||"salary";applyTheme();renderAll();renderPdfList()}
initialize();
